### ISSUE TITLE
Service that returns themes as JSON

### ISSUE THREAD

**Issue by Larkenx** [lysyi3m/macos-terminal-themes#39]
Hi,

Just wanted to share that I wrote up a nodejs express service that can read these themes in and serve them as JSON. You can find the code here https://github.com/Larkenx/extended-ascii-previewer/blob/master/server.js#L39. It uses `plist` to grab the Base64 Encoded serialized color strings and a regular expression to grab the RGB values. From there, it converts it to a hex. Here's an example output for a theme:

```json
{
      "name": "Afterglow",
      "Black": "#151515",
      "Blue": "#6c99ba",
      "BrightBlack": "#505050",
      "BrightBlue": "#6c99ba",
      "BrightCyan": "#7dd5cf",
      "BrightGreen": "#7e8d50",
      "BrightMagenta": "#9e4e85",
      "BrightRed": "#ac4142",
      "BrightWhite": "#f5f5f5",
      "BrightYellow": "#e5b566",
      "Cyan": "#7dd5cf",
      "Green": "#7e8d50",
      "Magenta": "#9e4e85",
      "Red": "#ac4142",
      "White": "#d0d0d0",
      "Yellow": "#e5b566",
      "Background": "#202020"
    }
```
You can fetch all of themes as JSON on my heroku hosted API at https://extended-ascii-viewer.herokuapp.com/color-themes.

**Comment by lysyi3m** [comment]
Hi, @Larkenx ! That's a great work. Just a suggestion here: since this repo is about macOS Terminal themes, which are xml files with color values generated by macOS Framework's `NSKeyedArchiver` (Terminal-specific format), it could be easier to rely on iterm2 schemes themselves, which are plain xml dicts with the following structure:

```
<key>Blue Component</key>
<real>0.0</real>
<key>Green Component</key>
<real>0.011764705882352941</real>
<key>Red Component</key>
<real>0.03529411764705882</real>
```

You can find iterm2 schemes here https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/schemes

Cheers!
